Made About Us section responsive and Prettier Formatted
glugmvit/gwoc pull request #14
Opened 2020-10-24 09:50 UTC by aa-deet-eeya

- Formatted the whole codebase using Prettier
- Added prettierrc.json
- Made About Us Responsive

2020-10-25 12:01 UTC, cseas requested changes
Please remove the `public/css/` files formatting. Those files just became much larger in size and harder to read. That's counter-intuitive to the purpose of formatting.

2020-10-25 12:01 UTC, cseas commented on package.json
> +    "format" : "prettier --write ./"
I'm not sure if setting the path as `./` is the best idea since this might format files we don't want to be touched, like `node_modules` or `build`.

What do you think about explicitly setting the paths to be formatted? [Check this](https://github.com/hazel-ui/hazel-ui/blob/e26175a96ccad27e7f73e21bc72406e18e2584b9/package.json#L14).

In our case, the script can be:
```json
"prettier:fix": "prettier --write \"{public,src}/**/*.{js,jsx,json,yml,md,mdx}\"",
```

2020-10-25 12:01 UTC, cseas commented on public/css/font-awesome/css/font-awesome.min.css
> +@font-face {
Minified files aren't meant to be formatted. That defeats the purpose of minification.

2020-10-25 12:01 UTC, cseas commented on package.json
> +    "format" : "prettier --write ./"
I assume this script is the reason there are formatted minified files in this PR. So we already know it's formatting things we don't want it to.

2020-10-25 12:01 UTC, cseas commented on public/css/default.css
> +      HTML5 Doctor Reset - html5doctor.com/html-5-reset-stylesheet/
This formatting seems unnecessary too. Makes the code harder to read. Maybe put `public/css/` folder in a `.prettierignore`. I'll ignore reviewing the other `public/css/` files in this PR since it's probably better to leave them like they are.

2020-10-25 12:15 UTC, cseas commented on package.json
> +    "format" : "prettier --write ./"
Looks like this one's a heated issue in the Prettier community and the maintainers don't seem to be very cooperative about it:
https://github.com/prettier/prettier/issues/5948

Let's put `public/css/` in a `.prettierignore` for now, that seems to be the best alternative.

2020-10-25 14:36 UTC, aa-deet-eeya commented on package.json
> +    "format" : "prettier --write ./"
Let's ignore the whole public for now, there are some minified dependencies there in `public/js`
What do you think?

2020-10-26 00:50 UTC, cseas commented on package.json
> +    "format" : "prettier --write ./"
Sure thing, we can ignore public. I think most of the formatting there is a good default that should be left untouched.

2020-10-26 01:04 UTC, cseas approved these changes

2020-10-26 01:04 UTC, cseas commented on .prettierignore
> +*.css
Let's replace this with `public/`. Any css added in `src/` for component specific styles should be formatted.

2020-10-26 01:04 UTC, cseas commented on package.json
> +    "prettier:fix": "prettier --write \"src/**/*.{js,jsx,json,yml,md,mdx}\""
Maybe add CSS extension as well and just put `public/` in `.prettierignore`

2020-10-26 01:06 UTC, cseas commented
Looks good to merge now. Left some suggestions above.

2020-10-26 06:33 UTC, merged